apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.deployment.name}}
  labels:
    app: analytics-service-app
    workload: {{.Values.deployment.name}}
spec:
  replicas: {{.Values.deployment.replicaCount}}
  selector:
    matchLabels:
      app: analytics-service-app
      workload: {{.Values.deployment.name}}
  template:
    metadata:
      labels:
        app: analytics-service-app
        workload: {{.Values.deployment.name}}
    spec:
      volumes:
        - name: google-cloud-key
          secret:
            secretName: analytics-service-sa-key
      containers:
        - name: {{.Values.deployment.name}}
          image: "gcr.io/single-system-dev/analytics-service:{{.Values.app.version}}"
          resources:
            requests:
              cpu: {{ .Values.deployment.containers.resources.requests.cpu }}
              memory: {{ .Values.deployment.containers.resources.requests.memory }}
            limits:
              cpu: {{ .Values.deployment.containers.resources.limits.cpu }}
              memory: {{ .Values.deployment.containers.resources.limits.memory }}
          ports:
            - containerPort: {{.Values.deployment.port}}
            - containerPort: {{.Values.actuator.server.port}}
          volumeMounts:
            - name: google-cloud-key
              mountPath: /var/secrets/google
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /var/secrets/google/key.json
            - name: MONGODB_USERNAME
              value: "{{ .Values.deployment.mongo.username}}"
            - name: MONGODB_PASSWORD
              value: "{{ .Values.deployment.mongo.password}}"
            - name: MONGODB_HOST
              value: "{{ .Values.deployment.mongo.host}}"
            - name: MONGODB_PORT
              value: "{{ .Values.deployment.mongo.port}}"
            - name: MONGODB_DATABASE
              value: "{{ .Values.deployment.mongo.database}}"
            - name: SERVER_PORT
              value: "{{ .Values.deployment.port}}"
            - name: KAFKA_BOOTSTRAP_SERVER
              value: "{{ .Values.deployment.kafka.bootstrap.server}}"
            - name: ACTUATOR_PORT
              value: "{{ .Values.actuator.server.port}}"
            - name: ACTUATOR_EXPOSE_ENDPOINTS
              value: "{{ .Values.actuator.endpoints.web.exposure.include}}"
            - name: TENANTS_SENDING_DATA
              value: "{{ .Values.deployment.kafka.topics.tenantsSendingData}}"
            - name: JDK_JAVA_OPTIONS
              value: "{{ .Values.env.JDK_JAVA_OPTIONS }}"