deployment:
  name: analytics-service
  replicaCount: 1
  port: 9036
  containers:
    resources:
      requests:
        cpu: 100m
        memory: 512Mi
      limits:
        cpu: 1000m
        memory: 4Gi
  mongo:
    database: analytics-service
    username: root
    host: my-release-mongodb.default.svc.cluster.local
    port: 27017
    password: ${sm://mongo-admin-password}
  kafka:
    bootstrap:
      server: 10.60.11.131:9092
    topics:
      tenantsSendingData: tenants-sending-data
service:
  target:
    port: 9036
actuator:
  server:
    port: 8077
  endpoints:
    web:
      exposure:
        include: '*'
env:
  JDK_JAVA_OPTIONS: "-Xmx3584M"